### ISSUE TITLE
FAQs aren't very Google-friendly

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#1]
It doesn't seem to know about their individual pages. We should probably have the FAQ just link to the individual pages

**Comment by wpsmort** [comment]
We are submitting FAQs to Google as separate unique pages on our XML Sitemap and Google is picking them up and showing them when I do a site search for:

site:semperplugins.com/faqs/

**Comment by michaeltorbert** [comment]
@wpsmort 
Maybe it just picks them up slowly?
We should make them crawlable. I don't think anything links to them other than the sitemap.
