### ISSUE TITLE
update for retina

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#10]
We need graphics appropriate for retina displays.

<img width="1144" alt="screen shot 2016-04-26 at 2 19 13 pm" src="https://cloud.githubusercontent.com/assets/17364998/14829561/0feb1646-0bba-11e6-93dd-6d82b28ae1fb.png">
<img width="1294" alt="screen shot 2016-04-26 at 2 18 58 pm" src="https://cloud.githubusercontent.com/assets/17364998/14829562/0feb7a00-0bba-11e6-9808-9aee6c6f5dfa.png">
<img width="1159" alt="screen shot 2016-04-26 at 2 18 52 pm" src="https://cloud.githubusercontent.com/assets/17364998/14829560/0fe897fe-0bba-11e6-9703-37ec18b6586e.png">

**Comment by wpsmort** [comment]
Closing this, all image improvement work is being done under Issue #18
