### ISSUE TITLE
check theme for hard-coded links

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#14]
considering potential ssl/https issues

**Comment by wpsmort** [comment]
The theme has been checked, the only hardcoded links are links to external stylesheets, i.e.

@import url("https://netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.css");
@import url('https://fonts.googleapis.com/css?family=PT+Serif:400,700');
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,700');
