### ISSUE TITLE
check h1, h2 tags for every type of page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#15]
Home page, product pages, posts, pages, etc. Make sure we're using header tags correctly

**Comment by wpsmort** [comment]
This is now done with the exception of the main Support page which is missing the H1 page title because of a confirmed bug in Simple:Press. Andy at Simple:Press said they are working on fixing this.

**Comment by wpsmort** [comment]
This is now fixed for the Support page as well.
