### ISSUE TITLE
Single product is off center on mobile

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#16]
![img_0560](https://cloud.githubusercontent.com/assets/17364998/15160047/cfaca4a2-16c5-11e6-9f37-d89ffe33a30d.PNG)

**Comment by wpsmort** [comment]
I reached out to Nadhir Boukhe on Fiverr to se if he wants to do this work for us.  He is in exams until June 4th.

**Comment by arnaudbroes** [comment]
I'll contact him. :-)

**Comment by arnaudbroes** [comment]
After slow communication and not doing the work, Nadhir has left Fiverr. I'm looking for someone else, also to address the other issues.

**Comment by michaeltorbert** [comment]
He's here https://www.fiverr.com/nadhirboukhe and github.com/NadhirBoukhenifra

**Comment by arnaudbroes** [comment]
Well he told me he doesn't have time to do freelance work at the moment (he got a fulltime job somewhere) and deactivated his Gig on Fiverr. I didn't explain it well, apologies. I've hired someone else who's experienced in CSS, PHP and WordPress and he'll commit the changes on GitHub, Steve mentioned it as a must.

**Comment by arnaudbroes** [comment]
See #46.

**Comment by wpsmort** [comment]
This has been fixed as part of #60
