### ISSUE TITLE
Highlight mouseover/hover item in nav menu drowdown

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#17]
<img width="664" alt="screen shot 2016-05-10 at 8 54 36 pm" src="https://cloud.githubusercontent.com/assets/17364998/15166905/886fcdea-16f1-11e6-9f31-fc195950e7f3.png">

**Comment by NadhirBoukhenifra** [comment]
Hello,
change this lines :
`	.main-nav ul > li:hover,
	.main-nav ul > li.current_page_item,
	.main-nav ul > li.current-menu-item,
	.main-nav ul > li:hover > a,
	.main-nav ul > li.current_page_item > a,
	.main-nav ul > li.current-menu-item > a {
		background: none !important;
		background-image: none !important;
		color: #3F75F1;
	}
	.main-nav ul > li > ul > li.current-menu-item > a {
		color: #fff !important;	
	} 
`


to this lines
`	.main-nav ul > li:hover,
	.main-nav ul > li.current_page_item,
	.main-nav ul > li.current-menu-item,
	.main-nav ul > li:hover > a,
	.main-nav ul > li.current_page_item > a,
	.main-nav ul > li.current-menu-item > a {
		background: none !important;
		background-image: none !important;
		/* color: #3F75F1;*/
		color: #434f66 !important;
	}
	.main-nav ul > li > ul > li.current-menu-item > a {
		/*color: #fff !important;	*/
		color: #fff;	
	} `

and you can change the hover color!
![untitled-2](https://cloud.githubusercontent.com/assets/13006236/15267698/c34dc4f4-19c0-11e6-820c-a534f4327d59.png)

**Comment by NadhirBoukhenifra** [comment]
![00](https://cloud.githubusercontent.com/assets/13006236/15267711/fc26a32c-19c0-11e6-9358-68467c0f92bb.PNG)

**Comment by NadhirBoukhenifra** [comment]
![3](https://cloud.githubusercontent.com/assets/13006236/15267966/641954e6-19c8-11e6-95bd-a55b6ed1077c.PNG)

add this code for this result ! the Menu item still in blue Color and hover color changed! 

![1](https://cloud.githubusercontent.com/assets/13006236/15267969/7a12a43c-19c8-11e6-96ed-2cfa01835292.png)

`	.main-nav ul > li:hover,
	.main-nav ul > li.current_page_item,
	.main-nav ul > li.current-menu-item,
	.main-nav ul > li:hover > a,
	.main-nav ul > li.current_page_item > a,
	.main-nav ul > li.current-menu-item > a {
		background: none !important;
		background-image: none !important;
		color: #3F75F1 ;
	}
	.main-nav ul > li:hover > a:hover,
	.main-nav ul > li.current-menu-item > a {
		color:  #434f66 !important;
	}
	.main-nav ul > li > ul > li.current-menu-item > a {
		/*color: #fff !important;	*/
		color: #fff;
	} `

**Comment by wpsmort** [comment]
Thanks Nadhir.  The code works well.  This issue is now closed.
