### ISSUE TITLE
better images

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#18]
This is on an iPhone 6+

![image1](https://cloud.githubusercontent.com/assets/17364998/15167664/b6fe7e8e-16f8-11e6-9c80-029b4723768b.PNG)
![image2](https://cloud.githubusercontent.com/assets/17364998/15167668/ba0dffa0-16f8-11e6-997d-33af814c1253.PNG)

**Comment by wpsmort** [comment]
I have added better quality images but will need to test this on iPhone once it's pushed to the live site.

**Comment by michaeltorbert** [comment]
@wpsmort  This has been pushed to the live site.

**Comment by arnaudbroes** [comment]
Images are ordered.
