### ISSUE TITLE
We should include the author name, category, date, etc on blog page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#22]
<img width="947" alt="screen shot 2016-05-11 at 4 38 24 pm" src="https://cloud.githubusercontent.com/assets/17364998/15195692/ec930c4c-1796-11e6-9538-29acad5a83b5.png">
<img width="1280" alt="screen shot 2016-05-11 at 4 38 11 pm" src="https://cloud.githubusercontent.com/assets/17364998/15195695/ee37feae-1796-11e6-83ce-de716dab0c46.png">

**Comment by wpsmort** [comment]
This is done in revision 114
