### ISSUE TITLE
Add latest posts to the homepage

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/semperpluginstheme#25]
Add latest four posts and style

**Comment by wpsmort** [comment]
I reached out to Nadhir Boukhe on Fiverr to se if he wants to do this work for us.  He is in exams until June 4th.

**Comment by wpsmort** [comment]
Here's an example of how we want this styled.

<img width="1313" alt="screen shot 2016-06-15 at 10 23 06 am" src="https://cloud.githubusercontent.com/assets/17548525/16083536/54b25e2e-32e3-11e6-803b-c751c61c2dfd.png">

**Comment by arnaudbroes** [comment]
I have a developer working on the issues, hope I get back some results this week.

**Comment by arnaudbroes** [comment]
See #46.

**Comment by wpsmort** [comment]
This is now done and tested.  The same styles also apply to the new Video page (#46).
