### ISSUE TITLE
add unique _get variables to buy now links we can identify purchasers that clicked it

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#27]
1) "buy now" button on homepage
2) product link next to subscribe2 and wpmq
3) menu
4) anything else?

This is the same as what we do in AIOSEOP. Pro upgrade links have something like ?loc=side/meta/etc on the end of them.

**Comment by wpsmort** [comment]
I have added the following variables:

Homepage button - ?loc=sp_homebtn
Homepage product - ?loc=sp_homeproduct
Documentation - ?loc=sp_docs
FAQs - ?loc=sp_faqs
Videos - ?loc=sp_videos
Main menu - ?loc=sp_navmenu
