### ISSUE TITLE
rrssb tag showing up

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#36]
<img width="704" alt="screen shot 2016-05-22 at 3 40 23 pm" src="https://cloud.githubusercontent.com/assets/17364998/15456079/b985d2a8-2033-11e6-9386-ad9014c5f236.png">

**Comment by wpsmort** [comment]
This has been fixed by installing our Responsive Social Sharing Buttons plugin.
