### ISSUE TITLE
Layout images should be in theme, not /uploads/

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#37]
This accomplishes several things... 

1) images that don't carry over to a new theme don't stick around for all eternity
2) updating a layout image don't have to be duplicated on every single dev site in addition to live

While there's certainly an overlap between what is or isn't a layout image, I'd put **almost** anything that isn't part of a blog post in this category... basically if it can change one day, particularly if it would likely change with a different theme

**Comment by michaeltorbert** [comment]
related to #38

**Comment by wpsmort** [comment]
All theme images have been migrated.
