### ISSUE TITLE
on mobile, the excerpt (formerly ACF) doesn't condense the same

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#42]
Compare dev to the live site... I'm not sure that it's even bad, but it's different, and isn't immediately obvious why.
<img width="785" alt="screen shot 2016-05-24 at 7 29 28 pm" src="https://cloud.githubusercontent.com/assets/17364998/15523118/08035eec-21e6-11e6-8304-848a0a7ce059.png">

**Comment by wpsmort** [comment]
This is fixed.
