### ISSUE TITLE
Taxonomy archive pages aren't paginated

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#50]
https://semperplugins.com/sections/api/
I'm not sure if this is a theme or plugin issue.

**Comment by wpsmort** [comment]
This appears to be resolved.  The section archive shows the Older posts / Newer posts navigation links at the bottom and clicking them navigates you to page 2 and 3.

![screen-capture](https://cloud.githubusercontent.com/assets/17548525/21360317/6598fb40-c6ad-11e6-9f04-e4792649b9c5.png)
