### ISSUE TITLE
Ensure links show up in author bio for guest bloggers

### ISSUE THREAD

**Issue by arnaudbroes** [semperfiwebdesign/semperpluginstheme#67]
Find a way to make links show up in the author bio of our guest bloggers.

![image](https://cloud.githubusercontent.com/assets/18156697/23673344/435b72a4-0372-11e7-8e85-4312438f5415.png)

**Comment by michaeltorbert** [comment]
If the author enters a URL on his profile, it should now show up. (It was already showing up in the globe icon, but now it has the text too.)

**Comment by arnaudbroes** [comment]
I confirm this works.
