### ISSUE TITLE
Add a counter to show amount earned by affiliates

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/semperpluginstheme#7]
Add a counter to the bottom of the homepage on the new site to show the amount of money earned by affiliates.  See the design here:

![semperplugins homepage v3 0](https://cloud.githubusercontent.com/assets/17548525/14540348/913f3720-0252-11e6-867e-f463fbc37fd6.jpg)

**Comment by michaeltorbert** [comment]
Did this in https://github.com/semperfiwebdesign/semperpluginstore/commit/adeade1fc293d36736423bc6a0ea93d819b39eac among others

**Comment by michaeltorbert** [comment]
@wpsmort This should be ready to go. It calculates, then uses transient caching (I think I set it to expire in a day or so) in order to not do the query and calculation on every home page load.

**Comment by wpsmort** [comment]
This looks to be working fine.
