### ISSUE TITLE
Add upsell to documentation pages

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/semperpluginstheme#73]
Add an upsell to each documentation page that states you can get help by purchasing AIOSEOP Pro and link to the product page.

**Comment by wpsmort** [comment]
This is ready for review.

**Comment by michaeltorbert** [comment]
@wpsmort 
-Make sure to use brackets after the if statement.
-Use === instead of ==
-Functions (like sfwd_remove_share_btns() and remove_filter()) should have spaces inside the parentheses: function( $variable ) not function($variable) 
-Commit changes to a branch and open a PR
