### ISSUE TITLE
Text being output in header when using double quotes in content

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/semperpluginstheme#74]
In the Documentation when double quotes followed by greater than symbols are used, spurious text content is output to the header.

http://spdev.dev/documentation/quick-start-guide/

<img width="1363" alt="screen shot 2017-06-30 at 3 33 49 pm" src="https://user-images.githubusercontent.com/17548525/27751283-8be888b8-5da9-11e7-868c-1ce78337f4d4.png">

**Comment by michaeltorbert** [comment]
@wpsmort Maybe I'm seeing things, but https://semperplugins.com/documentation/quick-start-guide/ doesn't have the blue area. Is this something in development?

**Comment by wpsmort** [comment]
@michaeltorbert Yes, that's new and is in the dev branch only.  It's related to Issue #73

**Comment by wpsmort** [comment]
This was actually caused by this bug in AIOSEOP which was fixed in v2.3.14 - https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/593
