### ISSUE TITLE
Optional Script to be put on footer

### ISSUE THREAD

**Issue by JohnHenryGaspay** [semperfiwebdesign/semperpluginstheme#76]
@michaeltorbert I think it would be better if could have an option to be put the script on footer section as it may affect the site performance on loading.

**Comment by michaeltorbert** [comment]
Which script?

**Comment by michaeltorbert** [comment]
@JohnHenryGaspay What script are you referring to?

**Comment by JohnHenryGaspay** [comment]
I'm referring to all tags like typical `<script>` instead putting it on header much better to put it on footer sample for that are: schema for website & analytics code.

**Comment by michaeltorbert** [comment]
I don't think this theme has any scripts in the header. https://github.com/semperfiwebdesign/semperpluginstheme/blob/master/header.php

**Comment by JohnHenryGaspay** [comment]
Hi I think I'm on the wrong place, I'm referring to the all-in-one SEO plugins not the theme.

**Comment by michaeltorbert** [comment]
@JohnHenryGaspay 
That repository is here: https://github.com/semperfiwebdesign/all-in-one-seo-pack
